Repository AGH-Narzedzia-Informatyczne-2022-2023/Snake, pull requests merged in 2022-11, with the labels that each got.

#7 Dodano podstawowy szkielet projektu
  constants.py
  main.py
Labels: core

#10 Added Score class
  score.py
Labels: enhancement

#8 Created Snake.py
  Snake.py
Labels: enhancement, question
